// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClothesService.proto

package LR_CA.SmartClothesService;

public interface ControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.ControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string TempControl1 = 1;</code>
   */
  java.lang.String getTempControl1();
  /**
   * <code>string TempControl1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getTempControl1Bytes();
}
