// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClothesService.proto

package LR_CA.SmartClothesService;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.Empty)
    com.google.protobuf.MessageOrBuilder {
}
