// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClothesService.proto

package LR_CA.SmartClothesService;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service2.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.service2.Message.Enum detail = 1;</code>
   */
  LR_CA.SmartClothesService.Message.Enum getDetail();
}
