// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClothesService.proto

package LR_CA.SmartClothesService;

/**
 * <pre>
 * That command its for CLIENT STREAMING RPC REQUEST
 * </pre>
 *
 * Protobuf type {@code service2.MovementsRequest}
 */
public  final class MovementsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service2.MovementsRequest)
    MovementsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MovementsRequest.newBuilder() to construct.
  private MovementsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MovementsRequest() {
    movementsRequest1_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MovementsRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            movementsRequest1_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return LR_CA.SmartClothesService.SmartClothesServicelmpl.internal_static_service2_MovementsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return LR_CA.SmartClothesService.SmartClothesServicelmpl.internal_static_service2_MovementsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LR_CA.SmartClothesService.MovementsRequest.class, LR_CA.SmartClothesService.MovementsRequest.Builder.class);
  }

  public static final int MOVEMENTSREQUEST1_FIELD_NUMBER = 1;
  private volatile java.lang.Object movementsRequest1_;
  /**
   * <code>string MovementsRequest1 = 1;</code>
   */
  public java.lang.String getMovementsRequest1() {
    java.lang.Object ref = movementsRequest1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      movementsRequest1_ = s;
      return s;
    }
  }
  /**
   * <code>string MovementsRequest1 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMovementsRequest1Bytes() {
    java.lang.Object ref = movementsRequest1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      movementsRequest1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMovementsRequest1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, movementsRequest1_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMovementsRequest1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, movementsRequest1_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LR_CA.SmartClothesService.MovementsRequest)) {
      return super.equals(obj);
    }
    LR_CA.SmartClothesService.MovementsRequest other = (LR_CA.SmartClothesService.MovementsRequest) obj;

    boolean result = true;
    result = result && getMovementsRequest1()
        .equals(other.getMovementsRequest1());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MOVEMENTSREQUEST1_FIELD_NUMBER;
    hash = (53 * hash) + getMovementsRequest1().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LR_CA.SmartClothesService.MovementsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LR_CA.SmartClothesService.MovementsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LR_CA.SmartClothesService.MovementsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LR_CA.SmartClothesService.MovementsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LR_CA.SmartClothesService.MovementsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LR_CA.SmartClothesService.MovementsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LR_CA.SmartClothesService.MovementsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LR_CA.SmartClothesService.MovementsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LR_CA.SmartClothesService.MovementsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LR_CA.SmartClothesService.MovementsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LR_CA.SmartClothesService.MovementsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LR_CA.SmartClothesService.MovementsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LR_CA.SmartClothesService.MovementsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * That command its for CLIENT STREAMING RPC REQUEST
   * </pre>
   *
   * Protobuf type {@code service2.MovementsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service2.MovementsRequest)
      LR_CA.SmartClothesService.MovementsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LR_CA.SmartClothesService.SmartClothesServicelmpl.internal_static_service2_MovementsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LR_CA.SmartClothesService.SmartClothesServicelmpl.internal_static_service2_MovementsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LR_CA.SmartClothesService.MovementsRequest.class, LR_CA.SmartClothesService.MovementsRequest.Builder.class);
    }

    // Construct using LR_CA.SmartClothesService.MovementsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      movementsRequest1_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return LR_CA.SmartClothesService.SmartClothesServicelmpl.internal_static_service2_MovementsRequest_descriptor;
    }

    @java.lang.Override
    public LR_CA.SmartClothesService.MovementsRequest getDefaultInstanceForType() {
      return LR_CA.SmartClothesService.MovementsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public LR_CA.SmartClothesService.MovementsRequest build() {
      LR_CA.SmartClothesService.MovementsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public LR_CA.SmartClothesService.MovementsRequest buildPartial() {
      LR_CA.SmartClothesService.MovementsRequest result = new LR_CA.SmartClothesService.MovementsRequest(this);
      result.movementsRequest1_ = movementsRequest1_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LR_CA.SmartClothesService.MovementsRequest) {
        return mergeFrom((LR_CA.SmartClothesService.MovementsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LR_CA.SmartClothesService.MovementsRequest other) {
      if (other == LR_CA.SmartClothesService.MovementsRequest.getDefaultInstance()) return this;
      if (!other.getMovementsRequest1().isEmpty()) {
        movementsRequest1_ = other.movementsRequest1_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      LR_CA.SmartClothesService.MovementsRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (LR_CA.SmartClothesService.MovementsRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object movementsRequest1_ = "";
    /**
     * <code>string MovementsRequest1 = 1;</code>
     */
    public java.lang.String getMovementsRequest1() {
      java.lang.Object ref = movementsRequest1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        movementsRequest1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string MovementsRequest1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMovementsRequest1Bytes() {
      java.lang.Object ref = movementsRequest1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        movementsRequest1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string MovementsRequest1 = 1;</code>
     */
    public Builder setMovementsRequest1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      movementsRequest1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string MovementsRequest1 = 1;</code>
     */
    public Builder clearMovementsRequest1() {
      
      movementsRequest1_ = getDefaultInstance().getMovementsRequest1();
      onChanged();
      return this;
    }
    /**
     * <code>string MovementsRequest1 = 1;</code>
     */
    public Builder setMovementsRequest1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      movementsRequest1_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service2.MovementsRequest)
  }

  // @@protoc_insertion_point(class_scope:service2.MovementsRequest)
  private static final LR_CA.SmartClothesService.MovementsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LR_CA.SmartClothesService.MovementsRequest();
  }

  public static LR_CA.SmartClothesService.MovementsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MovementsRequest>
      PARSER = new com.google.protobuf.AbstractParser<MovementsRequest>() {
    @java.lang.Override
    public MovementsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MovementsRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MovementsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MovementsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public LR_CA.SmartClothesService.MovementsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

