// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClothesService.proto

package LR_CA.SmartClothesService;

public interface MovementsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.MovementsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string MovementsRequest1 = 1;</code>
   */
  java.lang.String getMovementsRequest1();
  /**
   * <code>string MovementsRequest1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getMovementsRequest1Bytes();
}
