// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClothesService.proto

package LR_CA.SmartClothesService;

public final class SmartClothesServicelmpl {
  private SmartClothesServicelmpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_ControlRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_ControlRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_ControlResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_ControlResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_StretchingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_StretchingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_StretchingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_StretchingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031SmartClothesService.proto\022\010service2\"&\n" +
      "\016ControlRequest\022\024\n\014TempControl1\030\001 \001(\t\"\'\n" +
      "\017ControlResponse\022\024\n\014TempControl1\030\001 \001(\t\"(" +
      "\n\021StretchingRequest\022\023\n\013Stretching1\030\001 \001(\t" +
      "\")\n\022StretchingResponse\022\023\n\013Stretching1\030\001 " +
      "\001(\t\"Y\n\007Message\022&\n\006detail\030\001 \001(\0162\026.service" +
      "2.Message.Enum\"&\n\004Enum\022\013\n\007UNKNOWN\020\000\022\007\n\003L" +
      "OW\020\001\022\010\n\004HIGH\020\002\"\007\n\005Empty2\265\001\n\023SmartClothes" +
      "Service\022J\n\017bodyTempControl\022\030.service2.Co" +
      "ntrolRequest\032\031.service2.ControlResponse\"" +
      "\000(\001\022R\n\021musclesStretching\022\033.service2.Stre" +
      "tchingRequest\032\034.service2.StretchingRespo" +
      "nse(\0010\001B6\n\031LR_CA.SmartClothesServiceB\027Sm" +
      "artClothesServicelmplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_ControlRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_ControlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_ControlRequest_descriptor,
        new java.lang.String[] { "TempControl1", });
    internal_static_service2_ControlResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_ControlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_ControlResponse_descriptor,
        new java.lang.String[] { "TempControl1", });
    internal_static_service2_StretchingRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_StretchingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_StretchingRequest_descriptor,
        new java.lang.String[] { "Stretching1", });
    internal_static_service2_StretchingResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service2_StretchingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_StretchingResponse_descriptor,
        new java.lang.String[] { "Stretching1", });
    internal_static_service2_Message_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service2_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_service2_Empty_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service2_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
