// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartClothesService.proto

package LR_CA.SmartClothesService;

public interface StretchingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.StretchingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Stretching1 = 1;</code>
   */
  java.lang.String getStretching1();
  /**
   * <code>string Stretching1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getStretching1Bytes();
}
