// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FitnessTrackersService.proto

package LR_CA.FitnessTrackersService;

public interface BloodPressureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.BloodPressureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string BPressure1 = 1;</code>
   */
  java.lang.String getBPressure1();
  /**
   * <code>string BPressure1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getBPressure1Bytes();
}
