// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FitnessTrackersService.proto

package LR_CA.FitnessTrackersService;

public final class FitnessTrackersServicelmpl {
  private FitnessTrackersServicelmpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_StepsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_StepsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_StepsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_StepsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_MonitorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_MonitorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_MonitorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_MonitorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_BloodPressureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_BloodPressureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_BloodPressureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_BloodPressureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034FitnessTrackersService.proto\022\010service2" +
      "\"\035\n\014StepsRequest\022\r\n\005Steps\030\001 \001(\t\"\036\n\rSteps" +
      "Response\022\r\n\005Steps\030\001 \001(\t\"\"\n\016MonitorReques" +
      "t\022\020\n\010Monitor1\030\001 \001(\t\"#\n\017MonitorResponse\022\020" +
      "\n\010Monitor1\030\001 \001(\t\"*\n\024BloodPressureRequest" +
      "\022\022\n\nBPressure1\030\001 \001(\t\"+\n\025BloodPressureRes" +
      "ponse\022\022\n\nBPressure1\030\001 \001(\t\"Y\n\007Message\022&\n\006" +
      "detail\030\001 \001(\0162\026.service2.Message.Enum\"&\n\004" +
      "Enum\022\013\n\007UNKNOWN\020\000\022\007\n\003LOW\020\001\022\010\n\004HIGH\020\002\"\007\n\005" +
      "Empty2\214\002\n\026FitnessTrackersService\022F\n\rnumb" +
      "erOfSteps\022\026.service2.StepsRequest\032\027.serv" +
      "ice2.StepsResponse\"\000(\0010\001\022M\n\020heartRateMon" +
      "itor\022\030.service2.MonitorRequest\032\031.service" +
      "2.MonitorResponse\"\000(\0010\001\022[\n\024bloodPressure" +
      "Monitor\022\036.service2.BloodPressureRequest\032" +
      "\037.service2.BloodPressureResponse(\0010\001B<\n\034" +
      "LR_CA.FitnessTrackersServiceB\032FitnessTra" +
      "ckersServicelmplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_StepsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_StepsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_StepsRequest_descriptor,
        new java.lang.String[] { "Steps", });
    internal_static_service2_StepsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_StepsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_StepsResponse_descriptor,
        new java.lang.String[] { "Steps", });
    internal_static_service2_MonitorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_MonitorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_MonitorRequest_descriptor,
        new java.lang.String[] { "Monitor1", });
    internal_static_service2_MonitorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service2_MonitorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_MonitorResponse_descriptor,
        new java.lang.String[] { "Monitor1", });
    internal_static_service2_BloodPressureRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service2_BloodPressureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_BloodPressureRequest_descriptor,
        new java.lang.String[] { "BPressure1", });
    internal_static_service2_BloodPressureResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service2_BloodPressureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_BloodPressureResponse_descriptor,
        new java.lang.String[] { "BPressure1", });
    internal_static_service2_Message_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_service2_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_service2_Empty_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_service2_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
