// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FitnessTrackersService.proto

package LR_CA.FitnessTrackersService;

public final class FitnessTrackersServicelmpl {
  private FitnessTrackersServicelmpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_StepsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_StepsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_StepsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_StepsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_MonitorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_MonitorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_MonitorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_MonitorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034FitnessTrackersService.proto\022\010service2" +
      "\"\035\n\014StepsRequest\022\r\n\005Steps\030\001 \001(\t\"\037\n\rSteps" +
      "Response\022\016\n\006output\030\001 \001(\t\"\"\n\016MonitorReque" +
      "st\022\020\n\010Monitor1\030\001 \001(\t\"#\n\017MonitorResponse\022" +
      "\020\n\010Monitor1\030\001 \001(\t2\255\001\n\026FitnessTrackersSer" +
      "vice\022D\n\rnumberOfSteps\022\026.service2.StepsRe" +
      "quest\032\027.service2.StepsResponse\"\000(\001\022M\n\020he" +
      "artRateMonitor\022\030.service2.MonitorRequest" +
      "\032\031.service2.MonitorResponse\"\000(\0010\001B<\n\034LR_" +
      "CA.FitnessTrackersServiceB\032FitnessTracke" +
      "rsServicelmplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_StepsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_StepsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_StepsRequest_descriptor,
        new java.lang.String[] { "Steps", });
    internal_static_service2_StepsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_StepsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_StepsResponse_descriptor,
        new java.lang.String[] { "Output", });
    internal_static_service2_MonitorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_MonitorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_MonitorRequest_descriptor,
        new java.lang.String[] { "Monitor1", });
    internal_static_service2_MonitorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service2_MonitorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_MonitorResponse_descriptor,
        new java.lang.String[] { "Monitor1", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
