// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FitnessTrackersService.proto

package LR_CA.FitnessTrackersService;

public interface MonitorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.MonitorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Monitor1 = 1;</code>
   */
  java.lang.String getMonitor1();
  /**
   * <code>string Monitor1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getMonitor1Bytes();
}
