// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FitnessTrackersService.proto

package LR_CA.FitnessTrackersService;

public interface StepsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.StepsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Steps = 1;</code>
   */
  java.lang.String getSteps();
  /**
   * <code>string Steps = 1;</code>
   */
  com.google.protobuf.ByteString
      getStepsBytes();
}
