// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FitnessTrackersService.proto

package LR_CA.FitnessTrackersService;

public interface StepsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.StepsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string output = 1;</code>
   */
  java.lang.String getOutput();
  /**
   * <code>string output = 1;</code>
   */
  com.google.protobuf.ByteString
      getOutputBytes();
}
