// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RingMouseControlService.proto

package LR_CA.RingMouseControlService;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.Empty)
    com.google.protobuf.MessageOrBuilder {
}
