// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RingMouseControlService.proto

package LR_CA.RingMouseControlService;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.service1.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.service1.Message.Enum detail = 1;</code>
   */
  LR_CA.RingMouseControlService.Message.Enum getDetail();
}
