// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RingMouseControlService.proto

package LR_CA.RingMouseControlService;

/**
 * <pre>
 * That command its for Unary RPC RESPONSE
 * </pre>
 *
 * Protobuf type {@code service1.MoveResponse}
 */
public  final class MoveResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service1.MoveResponse)
    MoveResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MoveResponse.newBuilder() to construct.
  private MoveResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MoveResponse() {
    right2_ = "";
    left2_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MoveResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            right2_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            left2_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return LR_CA.RingMouseControlService.RingMouseControlServicelmpl.internal_static_service1_MoveResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return LR_CA.RingMouseControlService.RingMouseControlServicelmpl.internal_static_service1_MoveResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LR_CA.RingMouseControlService.MoveResponse.class, LR_CA.RingMouseControlService.MoveResponse.Builder.class);
  }

  public static final int RIGHT2_FIELD_NUMBER = 1;
  private volatile java.lang.Object right2_;
  /**
   * <code>string Right2 = 1;</code>
   */
  public java.lang.String getRight2() {
    java.lang.Object ref = right2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      right2_ = s;
      return s;
    }
  }
  /**
   * <code>string Right2 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRight2Bytes() {
    java.lang.Object ref = right2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      right2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEFT2_FIELD_NUMBER = 2;
  private volatile java.lang.Object left2_;
  /**
   * <code>string left2 = 2;</code>
   */
  public java.lang.String getLeft2() {
    java.lang.Object ref = left2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      left2_ = s;
      return s;
    }
  }
  /**
   * <code>string left2 = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLeft2Bytes() {
    java.lang.Object ref = left2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      left2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRight2Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, right2_);
    }
    if (!getLeft2Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, left2_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRight2Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, right2_);
    }
    if (!getLeft2Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, left2_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LR_CA.RingMouseControlService.MoveResponse)) {
      return super.equals(obj);
    }
    LR_CA.RingMouseControlService.MoveResponse other = (LR_CA.RingMouseControlService.MoveResponse) obj;

    boolean result = true;
    result = result && getRight2()
        .equals(other.getRight2());
    result = result && getLeft2()
        .equals(other.getLeft2());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RIGHT2_FIELD_NUMBER;
    hash = (53 * hash) + getRight2().hashCode();
    hash = (37 * hash) + LEFT2_FIELD_NUMBER;
    hash = (53 * hash) + getLeft2().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LR_CA.RingMouseControlService.MoveResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LR_CA.RingMouseControlService.MoveResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LR_CA.RingMouseControlService.MoveResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LR_CA.RingMouseControlService.MoveResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LR_CA.RingMouseControlService.MoveResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LR_CA.RingMouseControlService.MoveResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LR_CA.RingMouseControlService.MoveResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LR_CA.RingMouseControlService.MoveResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LR_CA.RingMouseControlService.MoveResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LR_CA.RingMouseControlService.MoveResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LR_CA.RingMouseControlService.MoveResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LR_CA.RingMouseControlService.MoveResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LR_CA.RingMouseControlService.MoveResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * That command its for Unary RPC RESPONSE
   * </pre>
   *
   * Protobuf type {@code service1.MoveResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service1.MoveResponse)
      LR_CA.RingMouseControlService.MoveResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LR_CA.RingMouseControlService.RingMouseControlServicelmpl.internal_static_service1_MoveResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LR_CA.RingMouseControlService.RingMouseControlServicelmpl.internal_static_service1_MoveResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LR_CA.RingMouseControlService.MoveResponse.class, LR_CA.RingMouseControlService.MoveResponse.Builder.class);
    }

    // Construct using LR_CA.RingMouseControlService.MoveResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      right2_ = "";

      left2_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return LR_CA.RingMouseControlService.RingMouseControlServicelmpl.internal_static_service1_MoveResponse_descriptor;
    }

    @java.lang.Override
    public LR_CA.RingMouseControlService.MoveResponse getDefaultInstanceForType() {
      return LR_CA.RingMouseControlService.MoveResponse.getDefaultInstance();
    }

    @java.lang.Override
    public LR_CA.RingMouseControlService.MoveResponse build() {
      LR_CA.RingMouseControlService.MoveResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public LR_CA.RingMouseControlService.MoveResponse buildPartial() {
      LR_CA.RingMouseControlService.MoveResponse result = new LR_CA.RingMouseControlService.MoveResponse(this);
      result.right2_ = right2_;
      result.left2_ = left2_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LR_CA.RingMouseControlService.MoveResponse) {
        return mergeFrom((LR_CA.RingMouseControlService.MoveResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LR_CA.RingMouseControlService.MoveResponse other) {
      if (other == LR_CA.RingMouseControlService.MoveResponse.getDefaultInstance()) return this;
      if (!other.getRight2().isEmpty()) {
        right2_ = other.right2_;
        onChanged();
      }
      if (!other.getLeft2().isEmpty()) {
        left2_ = other.left2_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      LR_CA.RingMouseControlService.MoveResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (LR_CA.RingMouseControlService.MoveResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object right2_ = "";
    /**
     * <code>string Right2 = 1;</code>
     */
    public java.lang.String getRight2() {
      java.lang.Object ref = right2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        right2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Right2 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRight2Bytes() {
      java.lang.Object ref = right2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        right2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Right2 = 1;</code>
     */
    public Builder setRight2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      right2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Right2 = 1;</code>
     */
    public Builder clearRight2() {
      
      right2_ = getDefaultInstance().getRight2();
      onChanged();
      return this;
    }
    /**
     * <code>string Right2 = 1;</code>
     */
    public Builder setRight2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      right2_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object left2_ = "";
    /**
     * <code>string left2 = 2;</code>
     */
    public java.lang.String getLeft2() {
      java.lang.Object ref = left2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        left2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string left2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLeft2Bytes() {
      java.lang.Object ref = left2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        left2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string left2 = 2;</code>
     */
    public Builder setLeft2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      left2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string left2 = 2;</code>
     */
    public Builder clearLeft2() {
      
      left2_ = getDefaultInstance().getLeft2();
      onChanged();
      return this;
    }
    /**
     * <code>string left2 = 2;</code>
     */
    public Builder setLeft2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      left2_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service1.MoveResponse)
  }

  // @@protoc_insertion_point(class_scope:service1.MoveResponse)
  private static final LR_CA.RingMouseControlService.MoveResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LR_CA.RingMouseControlService.MoveResponse();
  }

  public static LR_CA.RingMouseControlService.MoveResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MoveResponse>
      PARSER = new com.google.protobuf.AbstractParser<MoveResponse>() {
    @java.lang.Override
    public MoveResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MoveResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MoveResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MoveResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public LR_CA.RingMouseControlService.MoveResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

