// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RingMouseControlService.proto

package LR_CA.RingMouseControlService;

public interface MoveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.MoveResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Right2 = 1;</code>
   */
  java.lang.String getRight2();
  /**
   * <code>string Right2 = 1;</code>
   */
  com.google.protobuf.ByteString
      getRight2Bytes();

  /**
   * <code>string left2 = 2;</code>
   */
  java.lang.String getLeft2();
  /**
   * <code>string left2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getLeft2Bytes();
}
