// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RingMouseControlService.proto

package LR_CA.RingMouseControlService;

public interface MoveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.MoveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Right1 = 1;</code>
   */
  java.lang.String getRight1();
  /**
   * <code>string Right1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getRight1Bytes();

  /**
   * <code>string Left1 = 2;</code>
   */
  java.lang.String getLeft1();
  /**
   * <code>string Left1 = 2;</code>
   */
  com.google.protobuf.ByteString
      getLeft1Bytes();
}
