// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RingMouseControlService.proto

package LR_CA.RingMouseControlService;

/**
 * <pre>
 * define each variable in RPC method separately
 * That command its for unary RPC REQUEST
 * </pre>
 *
 * Protobuf type {@code service1.MoveRequest}
 */
public  final class MoveRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:service1.MoveRequest)
    MoveRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MoveRequest.newBuilder() to construct.
  private MoveRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MoveRequest() {
    right1_ = "";
    left1_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MoveRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            right1_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            left1_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return LR_CA.RingMouseControlService.RingMouseControlServicelmpl.internal_static_service1_MoveRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return LR_CA.RingMouseControlService.RingMouseControlServicelmpl.internal_static_service1_MoveRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LR_CA.RingMouseControlService.MoveRequest.class, LR_CA.RingMouseControlService.MoveRequest.Builder.class);
  }

  public static final int RIGHT1_FIELD_NUMBER = 1;
  private volatile java.lang.Object right1_;
  /**
   * <code>string Right1 = 1;</code>
   */
  public java.lang.String getRight1() {
    java.lang.Object ref = right1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      right1_ = s;
      return s;
    }
  }
  /**
   * <code>string Right1 = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRight1Bytes() {
    java.lang.Object ref = right1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      right1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LEFT1_FIELD_NUMBER = 2;
  private volatile java.lang.Object left1_;
  /**
   * <code>string Left1 = 2;</code>
   */
  public java.lang.String getLeft1() {
    java.lang.Object ref = left1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      left1_ = s;
      return s;
    }
  }
  /**
   * <code>string Left1 = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLeft1Bytes() {
    java.lang.Object ref = left1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      left1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRight1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, right1_);
    }
    if (!getLeft1Bytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, left1_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRight1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, right1_);
    }
    if (!getLeft1Bytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, left1_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LR_CA.RingMouseControlService.MoveRequest)) {
      return super.equals(obj);
    }
    LR_CA.RingMouseControlService.MoveRequest other = (LR_CA.RingMouseControlService.MoveRequest) obj;

    boolean result = true;
    result = result && getRight1()
        .equals(other.getRight1());
    result = result && getLeft1()
        .equals(other.getLeft1());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RIGHT1_FIELD_NUMBER;
    hash = (53 * hash) + getRight1().hashCode();
    hash = (37 * hash) + LEFT1_FIELD_NUMBER;
    hash = (53 * hash) + getLeft1().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LR_CA.RingMouseControlService.MoveRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LR_CA.RingMouseControlService.MoveRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LR_CA.RingMouseControlService.MoveRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LR_CA.RingMouseControlService.MoveRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LR_CA.RingMouseControlService.MoveRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LR_CA.RingMouseControlService.MoveRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LR_CA.RingMouseControlService.MoveRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LR_CA.RingMouseControlService.MoveRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LR_CA.RingMouseControlService.MoveRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LR_CA.RingMouseControlService.MoveRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LR_CA.RingMouseControlService.MoveRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LR_CA.RingMouseControlService.MoveRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LR_CA.RingMouseControlService.MoveRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * define each variable in RPC method separately
   * That command its for unary RPC REQUEST
   * </pre>
   *
   * Protobuf type {@code service1.MoveRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:service1.MoveRequest)
      LR_CA.RingMouseControlService.MoveRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LR_CA.RingMouseControlService.RingMouseControlServicelmpl.internal_static_service1_MoveRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LR_CA.RingMouseControlService.RingMouseControlServicelmpl.internal_static_service1_MoveRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LR_CA.RingMouseControlService.MoveRequest.class, LR_CA.RingMouseControlService.MoveRequest.Builder.class);
    }

    // Construct using LR_CA.RingMouseControlService.MoveRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      right1_ = "";

      left1_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return LR_CA.RingMouseControlService.RingMouseControlServicelmpl.internal_static_service1_MoveRequest_descriptor;
    }

    @java.lang.Override
    public LR_CA.RingMouseControlService.MoveRequest getDefaultInstanceForType() {
      return LR_CA.RingMouseControlService.MoveRequest.getDefaultInstance();
    }

    @java.lang.Override
    public LR_CA.RingMouseControlService.MoveRequest build() {
      LR_CA.RingMouseControlService.MoveRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public LR_CA.RingMouseControlService.MoveRequest buildPartial() {
      LR_CA.RingMouseControlService.MoveRequest result = new LR_CA.RingMouseControlService.MoveRequest(this);
      result.right1_ = right1_;
      result.left1_ = left1_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LR_CA.RingMouseControlService.MoveRequest) {
        return mergeFrom((LR_CA.RingMouseControlService.MoveRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LR_CA.RingMouseControlService.MoveRequest other) {
      if (other == LR_CA.RingMouseControlService.MoveRequest.getDefaultInstance()) return this;
      if (!other.getRight1().isEmpty()) {
        right1_ = other.right1_;
        onChanged();
      }
      if (!other.getLeft1().isEmpty()) {
        left1_ = other.left1_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      LR_CA.RingMouseControlService.MoveRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (LR_CA.RingMouseControlService.MoveRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object right1_ = "";
    /**
     * <code>string Right1 = 1;</code>
     */
    public java.lang.String getRight1() {
      java.lang.Object ref = right1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        right1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Right1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRight1Bytes() {
      java.lang.Object ref = right1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        right1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Right1 = 1;</code>
     */
    public Builder setRight1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      right1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Right1 = 1;</code>
     */
    public Builder clearRight1() {
      
      right1_ = getDefaultInstance().getRight1();
      onChanged();
      return this;
    }
    /**
     * <code>string Right1 = 1;</code>
     */
    public Builder setRight1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      right1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object left1_ = "";
    /**
     * <code>string Left1 = 2;</code>
     */
    public java.lang.String getLeft1() {
      java.lang.Object ref = left1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        left1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Left1 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLeft1Bytes() {
      java.lang.Object ref = left1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        left1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Left1 = 2;</code>
     */
    public Builder setLeft1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      left1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Left1 = 2;</code>
     */
    public Builder clearLeft1() {
      
      left1_ = getDefaultInstance().getLeft1();
      onChanged();
      return this;
    }
    /**
     * <code>string Left1 = 2;</code>
     */
    public Builder setLeft1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      left1_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:service1.MoveRequest)
  }

  // @@protoc_insertion_point(class_scope:service1.MoveRequest)
  private static final LR_CA.RingMouseControlService.MoveRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LR_CA.RingMouseControlService.MoveRequest();
  }

  public static LR_CA.RingMouseControlService.MoveRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MoveRequest>
      PARSER = new com.google.protobuf.AbstractParser<MoveRequest>() {
    @java.lang.Override
    public MoveRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MoveRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MoveRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MoveRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public LR_CA.RingMouseControlService.MoveRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

