// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RingMouseControlService.proto

package LR_CA.RingMouseControlService;

public final class RingMouseControlServicelmpl {
  private RingMouseControlServicelmpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_MoveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_MoveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_MoveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_MoveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_SelectObjectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_SelectObjectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_SelectObjectResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_SelectObjectResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035RingMouseControlService.proto\022\010service" +
      "1\",\n\013MoveRequest\022\016\n\006Right1\030\001 \001(\t\022\r\n\005Left" +
      "1\030\002 \001(\t\"-\n\014MoveResponse\022\016\n\006Right2\030\001 \001(\t\022" +
      "\r\n\005left2\030\002 \001(\t\"#\n\023SelectObjectRequest\022\014\n" +
      "\004Text\030\001 \001(\t\"$\n\024SelectObjectResponse\022\014\n\004T" +
      "ext\030\001 \001(\t\"Y\n\007Message\022&\n\006detail\030\001 \001(\0162\026.s" +
      "ervice1.Message.Enum\"&\n\004Enum\022\013\n\007UNKNOWN\020" +
      "\000\022\007\n\003LOW\020\001\022\010\n\004HIGH\020\002\"\007\n\005Empty2\250\002\n\027RingMo" +
      "useControlService\022D\n\021moveCursorToRight\022\025" +
      ".service1.MoveRequest\032\026.service1.MoveRes" +
      "ponse\"\000\022C\n\020moveCursorToLeft\022\025.service1.M" +
      "oveRequest\032\026.service1.MoveResponse\"\000\022-\n\005" +
      "empty\022\021.service1.Message\032\017.service1.Empt" +
      "y\"\000\022S\n\020SelectObjectText\022\035.service1.Selec" +
      "tObjectRequest\032\036.service1.SelectObjectRe" +
      "sponse0\001B>\n\035LR_CA.RingMouseControlServic" +
      "eB\033RingMouseControlServicelmplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_MoveRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_MoveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_MoveRequest_descriptor,
        new java.lang.String[] { "Right1", "Left1", });
    internal_static_service1_MoveResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_MoveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_MoveResponse_descriptor,
        new java.lang.String[] { "Right2", "Left2", });
    internal_static_service1_SelectObjectRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_SelectObjectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_SelectObjectRequest_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_service1_SelectObjectResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_SelectObjectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_SelectObjectResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_service1_Message_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service1_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_service1_Empty_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service1_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
