// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RingMouseControlService.proto

package LR_CA.RingMouseControlService;

public interface SelectObjectResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.SelectObjectResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <code>string Text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
